# Generated by Django 4.0.5 on 2023-04-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_banco', models.CharField(max_length=255)),
                ('planos', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('foto_cliente', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Faena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_faena', models.CharField(max_length=100)),
                ('foto_faena', models.FileField(blank=True, null=True, upload_to='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Faena',
                'verbose_name_plural': 'Faenas',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=100)),
                ('acronimo', models.CharField(blank=True, max_length=40, null=True)),
                ('lenguaje', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Pozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_pozo', models.CharField(max_length=255)),
                ('latitud', models.FloatField(blank=True)),
                ('longitud', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=100)),
                ('tipo_zona', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Zona de Servicio',
                'verbose_name_plural': 'Zonas de Servicios',
            },
        ),
        migrations.CreateModel(
            name='Poligono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_poligono', models.CharField(max_length=255)),
                ('plano_poligono', models.FileField(blank=True, null=True, upload_to='')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.banco')),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_operacion', models.CharField(max_length=100)),
                ('faena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.faena')),
            ],
            options={
                'verbose_name': 'Operacion',
                'verbose_name_plural': 'Operaciones',
            },
        ),
        migrations.CreateModel(
            name='Molino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_molino', models.CharField(max_length=255)),
                ('faena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.faena')),
            ],
            options={
                'verbose_name': 'Molino',
                'verbose_name_plural': 'Molinos',
            },
        ),
        migrations.CreateModel(
            name='Malla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_malla', models.CharField(max_length=255)),
                ('plano_malla', models.FileField(blank=True, null=True, upload_to='')),
                ('poligono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.poligono')),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fase', models.CharField(max_length=100)),
                ('planos', models.FileField(blank=True, null=True, upload_to='')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.operacion')),
            ],
        ),
        migrations.AddField(
            model_name='faena',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.pais'),
        ),
        migrations.CreateModel(
            name='Chancador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_chancador', models.CharField(max_length=255)),
                ('setting_objetivo', models.FloatField(blank=True)),
                ('nombre_chancador', models.CharField(max_length=255)),
                ('faena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.faena')),
            ],
            options={
                'verbose_name': 'Chancador',
                'verbose_name_plural': 'Chancadores',
            },
        ),
        migrations.AddField(
            model_name='banco',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.fase'),
        ),
    ]
