# Generated by Django 4.0.5 on 2023-04-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RPrimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FileRPrimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotica.rprimer')),
            ],
        ),
    ]
