# Generated by Django 4.0.5 on 2023-04-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geocerca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_geocerca', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=512, null=True)),
                ('faena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.faena')),
            ],
        ),
        migrations.CreateModel(
            name='TipoGeocerca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de Geocerca',
                'verbose_name_plural': 'Tipos de Geocercas',
            },
        ),
        migrations.CreateModel(
            name='PuntosGeocercas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('geocerca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geocercas.geocerca')),
            ],
            options={
                'verbose_name': 'Punto Geocerca',
                'verbose_name_plural': 'Puntos Geocercas',
            },
        ),
        migrations.AddField(
            model_name='geocerca',
            name='tipo_geocerca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geocercas.tipogeocerca'),
        ),
        migrations.AddField(
            model_name='geocerca',
            name='zona_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.zonaservicio'),
        ),
    ]
